### ISSUE TITLE
Create_Multi_hixe

### ISSUE THREAD

**Issue by NoeBerdoz** [CPNV-ES/hixe#10]

**Comment by gamars99** [comment]
# Quête: Create_Multi_hixe

Prise en charge le 05.02.2020, par Gaël Oberson

## Analyse
### Fonctionnement actuel

L'application Hixe ne permets pas d'ajouter plusieurs `Hike` simultanément

### Description du problème

Il va falloir gérer l’insertion multiple de `Hixe`

### Description de la solution

Création d'une page dédier à la création de plusieurs `Hixe` simultanément, avec un tableau regroupant toutes les `Hixe` a ajouter.

(Terminé, le 12.02.2020)

## Réalisation
### Plan d'intervention

- Création d'un __controller__ **MultiHixesController**  via la commande suivante :
   ```
    php artisan make:controller MultiHixesController
   ```
- Création d'une __vue__ **createHikes** 

   La vue contient le layout + le tableau d'insertion des `Hixes`

(Terminé, le 12.02.2020)

### Exécution

#### 07.02.2020

- Meeting avec le groupe Hixe + M. Carrel
- Création de la view
- Code de l'ajoute de ligne du tableau
- Code de la suppression de ligne du tableau
- Création du Controller

#### 12.02.2020

- Code de l'ajout multiple dans la DB
- Code de la validation d'entré et gestion d'erreur

### Tests

- L'ajout de plusieurs `Hixe` est possible.
- Le contrôle d'entrer fonctionner
- Aucun message d'erreur afficher lorsqu'un champs obligatoire n'est pas remplie.

(Terminés, le 12.02.2020)

### Commit

[Merge branch 'feature/Create_Multi_hixe' into develop](https://github.com/CPNV-ES/hixe/commit/59a0b41d3f0a76ebbc4af08ae0606c8fde778314)

(Fait, le 12.02.2020)
