### ISSUE TITLE
Doesn't mention any seeder in the documentation

### ISSUE THREAD

**Issue by SuperQuentin** [CPNV-ES/hixe#51]
We have a return from product owner there is no allusion in the documentation of the seeders

**Comment by MathieuBurnat** [comment]
https://icescrum.cpnv.ch/p/HIXE/#/taskBoard/993/task/6656

**Comment by MathieuBurnat** [comment]
It possible to see the last version of the readme [here](https://github.com/CPNV-ES/hixe/tree/develop#hixe). ;,)
