### ISSUE TITLE
The active tab in the header does not work on "Mes Courses"

### ISSUE THREAD

**Issue by AlexandrePhilibertCPNV** [CPNV-ES/hixe#53]
![Screenshot from 2021-05-06 09-55-43](https://user-images.githubusercontent.com/47384840/117262191-477eac00-ae51-11eb-899d-629cd550a457.png)

The "Mes courses" header should be active on the "/" route.

**Comment by SuperQuentin** [comment]
As been fixed by using this https://laravel.com/docs/6.x/routing#accessing-the-current-route and adding a name on naming route.
Remove handiest way to get a current view page
